# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28ececb8fff8f205b829ad4e7bbb0e28c59931fbba73eff4b505303b69c28a21a8725d5761e72f7a712a1021c8f392595ecab0cc97626fec1237ff96f89b7ec3

test:
  secret_key_base: 147e1f5b32d66675281fcaed404292973063a074121b53271cd234ba72fb05ee6847f7e4c1b02d491c288a10e3b95a82c4e03885827799e1b0c656fd9a4a89b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
